project: 
  type: website
  output-dir: docs

website:
  title: "Mutsa's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "TidyTuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Synthetic Data Exercise"
            file: syntheticdata-exercise/syntheticdata-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning Models Exercise"
            file: ml-models-exercise/ml-models-exercise.qmd
            
    right:
      - icon: github 
        href: https://github.com/MutsaN1/mutsanyamuranga-MADA-portfolio.git        

format:
  html:
    theme: solar
    highlight: zenburn
    css: styles.css
    toc: false